@baseUrl = http://localhost:3000

###PRODUCTS

### create Product
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "test",
    "price": 5000,
    "quantity": 50,
    "category": "Books"
}

### get all products
GET  {{baseUrl}}/products

### get product by id
GET  {{baseUrl}}/products/660812bd25e8b7040012f948

### upodate product 
PUT   {{baseUrl}}/products/660812bd25e8b7040012f948
Content-Type: application/json

{
    "name": "test update",
    "price": 5025,
    "category": "electronics"
}

### delete product by id
DELETE   {{baseUrl}}/products/660812bd25e8b7040012f948


### CATEGORIES

### create category
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "test-2"
}

### get all categories
GET  {{baseUrl}}/categories

### upodate categories 
PUT   {{baseUrl}}/categories/66081800067f451714607433
Content-Type: application/json

{
    "name": "test-2"
}

### delete categories
DELETE   {{baseUrl}}/categories/66081a4e11134f043e624da9