@baseUrl = http://localhost:3000

###PRODUCTS

### create Product
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "laptop",
    "price": 5000,
    "quantity": 50,
    "category": "66082666fce2cc75b77342d0"
}

### get all products
GET  {{baseUrl}}/products

### get product by id
GET  {{baseUrl}}/products/660826e62e2ad8b833948c46

### upodate product 
PUT   {{baseUrl}}/products/660826e62e2ad8b833948c46
Content-Type: application/json

{
    "name": "test update",
    "price": 5025,
    "category": "660820ecf45c961d11bd4d95"
}

### delete product by id
DELETE   {{baseUrl}}/products/660820c0f45c961d11bd4d88


### CATEGORIES

### create category
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "Electronics"
}

### get all categories
GET  {{baseUrl}}/categories

### upodate categories 
PUT   {{baseUrl}}/categories/66081800067f451714607433
Content-Type: application/json

{
    "name": "test-2"
}

### delete categories
DELETE   {{baseUrl}}/categories/660820ecf45c961d11bd4d95