@baseUrl = http://localhost:3000

### create Product
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "phone",
    "price": 5000,
    "quantity": 50,
    "category": "Books"
}

### get all products
GET  {{baseUrl}}/products

### get product by id
GET  {{baseUrl}}/products/6607f9e23c31bc176c490399
